CREATE TABLE site_terms (
  id CHAR(36) PRIMARY KEY,
  body_html TEXT NOT NULL DEFAULT (''),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
