CREATE TABLE oman_overviews (
  id CHAR(36) PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  pdf_url TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
