CREATE TABLE deals (
  id CHAR(36) PRIMARY KEY,
  title TEXT NOT NULL,
  duration TEXT,
  image_url TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
